-- Initial schema.
--
-- General rules:
--   * every table is STRICT — a typo in a type becomes a write error, not silent corruption;
--   * time is epoch ms (INTEGER) everywhere except sessions.date, which is the user's local date;
--   * updated_ts/updated_by are the clock and device used for last-write-wins;
--   * rev is the global monotone counter from meta; sync deltas are built from it.

CREATE TABLE meta (
  k TEXT PRIMARY KEY,
  v TEXT NOT NULL
) STRICT;

INSERT INTO meta(k, v) VALUES ('rev', '0');

-- Immutable, content-addressed program snapshots.
-- A program is attached to a user through users.current_program_hash and to history
-- through sessions.program_hash. That is why changing a program does not rewrite past workouts.
CREATE TABLE programs (
  hash       TEXT PRIMARY KEY,
  json       TEXT    NOT NULL,
  created_at INTEGER NOT NULL
) STRICT;

CREATE TABLE users (
  id                   INTEGER PRIMARY KEY,
  username             TEXT    NOT NULL COLLATE NOCASE UNIQUE,
  display_name         TEXT    NOT NULL DEFAULT '',
  password_hash        TEXT    NOT NULL,
  created_at           INTEGER NOT NULL,
  disabled             INTEGER NOT NULL DEFAULT 0 CHECK (disabled IN (0, 1)),
  is_admin             INTEGER NOT NULL DEFAULT 0 CHECK (is_admin IN (0, 1)),
  current_program_hash TEXT REFERENCES programs(hash)
) STRICT;

-- Only the hash of a token is stored: leaking the database does not grant a login.
CREATE TABLE auth_tokens (
  token_hash   BLOB    PRIMARY KEY,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at   INTEGER NOT NULL,
  last_seen_at INTEGER NOT NULL,
  expires_at   INTEGER NOT NULL,
  user_agent   TEXT    NOT NULL DEFAULT '',
  label        TEXT    NOT NULL DEFAULT ''
) STRICT;

CREATE INDEX ix_auth_tokens_user ON auth_tokens(user_id, expires_at);

-- The second brute-force layer: unlike an in-memory counter, this one survives a restart.
CREATE TABLE login_attempts (
  id       INTEGER PRIMARY KEY,
  at       INTEGER NOT NULL,
  ip       TEXT    NOT NULL,
  username TEXT    NOT NULL,
  ok       INTEGER NOT NULL CHECK (ok IN (0, 1))
) STRICT;

CREATE INDEX ix_login_attempts_user ON login_attempts(username, at);
CREATE INDEX ix_login_attempts_ip   ON login_attempts(ip, at);

CREATE TABLE sessions (
  id           TEXT    PRIMARY KEY,          -- UUIDv7 generated by the client (needed to start offline)
  user_id      INTEGER NOT NULL REFERENCES users(id),
  date         TEXT    NOT NULL,             -- 'YYYY-MM-DD', the user's local date
  day_id       TEXT    NOT NULL,
  program_hash TEXT    NOT NULL REFERENCES programs(hash),
  started_at   INTEGER NOT NULL,
  finished_at  INTEGER,                      -- NULL = unfinished
  deleted      INTEGER NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
  note         TEXT    NOT NULL DEFAULT '',
  updated_ts   INTEGER NOT NULL,
  updated_by   TEXT    NOT NULL DEFAULT '',
  rev          INTEGER NOT NULL
) STRICT;

-- "There can be only one unfinished workout" is a database invariant, not a check in code.
CREATE UNIQUE INDEX ux_sessions_one_open ON sessions(user_id)
  WHERE finished_at IS NULL AND deleted = 0;

CREATE INDEX ix_sessions_user_date ON sessions(user_id, date DESC);
CREATE INDEX ix_sessions_user_rev  ON sessions(user_id, rev);

-- idx is assigned once and NEVER renumbered: only that way is the composite key stable
-- and last-write-wins correct. Deletion is deleted=1, not a shift of the neighbours.
CREATE TABLE sets (
  session_id  TEXT    NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  exercise_id TEXT    NOT NULL,
  idx         INTEGER NOT NULL CHECK (idx >= 0),
  done        INTEGER NOT NULL DEFAULT 0 CHECK (done IN (0, 1)),
  weight      REAL,                          -- NULL = unweighted exercise, or no weight entered
  reps        TEXT,                          -- free-form, e.g. '12' | '8/нога' | '30с' | '40м'
  deleted     INTEGER NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
  updated_ts  INTEGER NOT NULL,
  updated_by  TEXT    NOT NULL DEFAULT '',
  rev         INTEGER NOT NULL,
  PRIMARY KEY (session_id, exercise_id, idx)
) STRICT, WITHOUT ROWID;

CREATE INDEX ix_sets_rev      ON sets(rev);
CREATE INDEX ix_sets_exercise ON sets(exercise_id, session_id);

-- The idempotence ledger: a redelivered batch is not applied twice.
CREATE TABLE applied_ops (
  op_id      TEXT    PRIMARY KEY,
  user_id    INTEGER NOT NULL,
  applied_at INTEGER NOT NULL
) STRICT;

CREATE INDEX ix_applied_ops_gc ON applied_ops(applied_at);
